# Generated by Django 5.2.6 on 2025-10-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sessionactividad_fecha_hora_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricacorazon',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
